import traceback
import pandas as pd

def execute_and_review(df, python_code):
    """
    Agent 3 (The Reviewer): Executes the code and verifies the output shape.
    """
    # Create a local environment with a copy of the dataframe
    local_env = {"df": df.copy(), "pd": pd}
    
    try:
        # Execute the python code generated by the Coder
        exec(python_code, globals(), local_env)
        
        # Extract the cleaned dataframe
        cleaned_df = local_env["df"]
        
        review = {
            "execution_success": True,
            "final_shape": cleaned_df.shape,
            "missing_values_remaining": cleaned_df.isnull().sum().to_dict(),
            "duplicates_remaining": int(cleaned_df.duplicated().sum()),
            "column_names": list(cleaned_df.columns)
        }
        
        return review, cleaned_df
        
    except Exception as e:
        review = {
            "execution_success": False,
            "error_message": str(e),
            "traceback": traceback.format_exc()
        }
        
        # Fallback to the original dataframe if execution fails
        return review, df